# device type: possible manufacturer
device_manufacturers = {
    "Firewall": ["Cisco Systems", "Fortinet", "Palo Alto Networks", "SonicWall", "Check Point Software"],
    "Router": ["Cisco Systems", "Juniper Networks", "Huawei Technologies", "Ubiquiti Networks", "MikroTik"],
    "Switch": ["Cisco Systems", "Arista Networks", "Hewlett Packard Enterprise (HPE)", "Extreme Networks", "Netgear"],
    "Load Balancer": ["F5 Networks", "Citrix", "A10 Networks", "Radware", "Barracuda Networks"],
    "Server": ["Dell Technologies", "Hewlett Packard Enterprise (HPE)", "Lenovo", "Huawei Technologies", "Cisco Systems"],
    "Network Gateway": ["Cisco Systems", "Juniper Networks", "Fortinet", "Palo Alto Networks", "Zyxel Communications"],
    "Access Point": ["Cisco Systems", "Ubiquiti Networks", "Aruba Networks", "Netgear", "Zyxel Communications"],
    "Virtual Machine": ["VMware", "Microsoft", "Citrix", "Oracle", "Red Hat"],
    "Proxy Server": ["F5 Networks", "Blue Coat Systems", "Squid", "Cisco Systems", "Barracuda Networks"],
    "Intrusion Detection System (IDS)": ["Cisco Systems", "Palo Alto Networks", "Fortinet", "Snort", "McAfee"],
    "Unified Threat Management (UTM)": ["Fortinet", "Sophos", "Cisco Systems", "WatchGuard", "Check Point Software"],
    "VPN Gateway": ["Cisco Systems", "Palo Alto Networks", "Fortinet", "SonicWall", "Barracuda Networks"],
    "Storage Area Network (SAN)": ["Dell Technologies", "Hewlett Packard Enterprise (HPE)", "NetApp", "IBM", "Hitachi"],
    "Web Application Firewall (WAF)": ["F5 Networks", "Imperva", "Barracuda Networks", "Fortinet", "Akamai"],
    "Endpoint Detection and Response (EDR)": ["CrowdStrike", "SentinelOne", "McAfee", "Symantec", "Carbon Black"],
    "Email Security Gateway": ["Barracuda Networks", "Proofpoint", "Cisco Systems", "Mimecast", "Fortinet"],
    "Data Loss Prevention (DLP)": ["Symantec", "McAfee", "Digital Guardian", "Forcepoint", "Cisco Systems"],
    "Identity and Access Management (IAM)": ["Okta", "Microsoft", "Ping Identity", "IBM", "SailPoint"],
    "Cloud Access Security Broker (CASB)": ["Netskope", "McAfee", "Microsoft", "Symantec", "Bitglass"],
    "Next-Generation Firewall (NGFW)": ["Palo Alto Networks", "Fortinet", "Cisco Systems", "Juniper Networks", "SonicWall"]
}

security_vulnerabilities = {
    "Unpatched Software": "Security vulnerabilities due to outdated or unpatched firmware or software.",
    "Default Passwords": "Devices with default or weak passwords that haven't been changed.",
    "Unencrypted Traffic": "Transmission of sensitive data without encryption.",
    "Open Ports": "Unnecessary or insecure open ports that expose services to the internet.",
    "Insecure APIs": "Vulnerabilities in application programming interfaces (APIs) that can be exploited.",
    "Weak Encryption": "Use of outdated or weak encryption algorithms.",
    "Unsecured Management Interfaces": "Management interfaces accessible without proper authentication or encryption.",
    "Improper Access Controls": "Inadequate access controls leading to unauthorized access.",
    "Firmware Spoofing": "Attacks that exploit vulnerabilities in device firmware.",
    "Misconfigured Firewalls": "Incorrectly configured firewalls allowing unauthorized access.",
    "Phishing Attacks": "Susceptibility to phishing attacks that trick users into revealing sensitive information.",
    "Cross-Site Scripting (XSS)": "Vulnerabilities allowing attackers to inject malicious scripts.",
    "SQL Injection": "Exploits that allow attackers to execute malicious SQL queries.",
    "Denial of Service (DoS)": "Vulnerabilities that can be exploited to overwhelm a service and make it unavailable.",
    "Buffer Overflow": "Attacks exploiting buffer overflow vulnerabilities in device software.",
    "Insecure Firmware Updates": "Unsecure methods for updating device firmware.",
    "Lack of Logging": "Insufficient logging of security-relevant events.",
    "Privilege Escalation": "Vulnerabilities that allow attackers to gain higher levels of access.",
    "Unvalidated Input": "Failure to properly validate input, leading to various attacks.",
    "Insufficient Authentication": "Weak authentication mechanisms that can be bypassed.",
    "Broken Cryptography": "Use of flawed cryptographic implementations or keys.",
    "Improper Session Management": "Inadequate handling of user sessions.",
    "Malware": "Devices compromised by malware or ransomware.",
    "Social Engineering": "Susceptibility to social engineering attacks targeting device users.",
    "Insecure Configuration": "Default or insecure configurations left on devices.",
    "Insecure Communication Protocols": "Use of outdated or insecure communication protocols.",
    "Data Leakage": "Accidental or intentional leakage of sensitive data.",
    "Insecure Cloud Storage": "Vulnerabilities in cloud storage configurations.",
    "Firmware Backdoors": "Hidden backdoors in device firmware allowing unauthorized access.",
    "Cross-Site Request Forgery (CSRF)": "Exploits that trick users into making unwanted requests.",
    "Insecure Device APIs": "APIs with inadequate security controls.",
    "Insecure Protocol Implementations": "Vulnerabilities in the implementation of network protocols.",
    "Lack of Endpoint Protection": "Absence of endpoint protection mechanisms like antivirus or EDR.",
    "Insecure Default Settings": "Devices shipped with insecure default settings.",
    "Inadequate Network Segmentation": "Lack of proper network segmentation to isolate sensitive areas.",
    "Unpatched Vulnerabilities": "Known vulnerabilities that have not been patched.",
    "Uncontrolled Device Access": "Lack of control over physical or remote access to devices.",
    "Insecure Wireless Configurations": "Weaknesses in wireless network configurations.",
    "Firmware Integrity Issues": "Problems with verifying the integrity of firmware updates.",
    "Improper Error Handling": "Failure to handle errors securely, exposing system information.",
    "Unsecure Backup Procedures": "Insecure methods for backing up device data.",
    "Insecure Development Practices": "Flaws introduced during the development phase.",
    "Insecure Device Management": "Weaknesses in the management and monitoring of devices.",
    "Exposure of Sensitive Data": "Unintended exposure of sensitive data to unauthorized parties.",
    "Uncontrolled Device Interfaces": "Insecure interfaces exposed to external networks.",
    "Insecure Device Lifecycle Management": "Weaknesses in managing the device lifecycle.",
    "Unprotected Administrative Interfaces": "Administrative interfaces without proper security measures.",
    "Lack of Encryption at Rest": "Sensitive data stored on devices without encryption.",
    "Unsecure Remote Access": "Vulnerabilities in remote access solutions.",
    "Inadequate Incident Response": "Weak incident response mechanisms for handling security breaches."
}
